# Generated by Django 2.2 on 2019-12-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.CharField(blank=True, db_column='CT', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=250, null=True)),
                ('estado', models.IntegerField(blank=True, db_column='Estado', null=True)),
                ('razonparo_fk', models.IntegerField(blank=True, db_column='RazonParo_fk', null=True)),
                ('planta_grupoct_fk', models.IntegerField(blank=True, db_column='Planta_GrupoCT_fk', null=True)),
                ('monitoreado', models.BooleanField(blank=True, db_column='Monitoreado', null=True)),
                ('cc', models.CharField(blank=True, db_column='CC', max_length=50, null=True)),
                ('publicartiemporeal', models.BooleanField(blank=True, db_column='PublicarTiempoReal', null=True)),
                ('activa', models.BooleanField(blank=True, db_column='Activa', null=True)),
                ('costostd', models.FloatField(blank=True, db_column='CostoStd', null=True)),
                ('loteprod_fk', models.IntegerField(blank=True, db_column='LoteProd_fk', null=True)),
                ('maxfechacarga', models.DateField(blank=True, db_column='MaxFechaCarga', null=True)),
                ('factorconversion', models.FloatField(blank=True, db_column='FactorConversion', null=True)),
                ('fcdesdect', models.BooleanField(blank=True, db_column='FCDesdeCT', null=True)),
                ('ultimolote', models.IntegerField(blank=True, db_column='UltimoLote', null=True)),
                ('nroetiquetasimpresionvariable', models.BooleanField(blank=True, db_column='NroEtiquetasImpresionVariable', null=True)),
                ('ordenescontroladasencentrotrabajo', models.IntegerField(blank=True, db_column='OrdenesControladasEnCentroTrabajo', null=True)),
                ('totalenmaquina', models.IntegerField(blank=True, db_column='TotalEnMaquina', null=True)),
                ('detalleparoactual', models.TextField(blank=True, db_column='DetalleParoActual', null=True)),
                ('enmantenimiento', models.BooleanField(blank=True, db_column='EnMantenimiento', null=True)),
            ],
            options={
                'db_table': 'CT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoparo', models.IntegerField(blank=True, db_column='tiempoParo', null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('codigoparo_fk', models.IntegerField(blank=True, db_column='codigoParo_fk', null=True)),
                ('job_fk', models.IntegerField(blank=True, null=True)),
                ('ct_fk', models.IntegerField(blank=True, db_column='CT_fk', null=True)),
                ('ciclosparos', models.IntegerField(blank=True, db_column='CiclosParos', null=True)),
                ('turno', models.IntegerField(blank=True, db_column='Turno', null=True)),
                ('fechacalc', models.DateField(blank=True, db_column='FechaCalc', null=True)),
            ],
            options={
                'db_table': 'Paros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='usuario', max_length=50, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='pass', max_length=100, null=True)),
                ('nivelacceso', models.IntegerField(blank=True, db_column='nivelAcceso', null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=50, null=True)),
                ('cargo', models.CharField(blank=True, db_column='Cargo', max_length=50, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
