# Generated by Django 2.2 on 2019-12-05 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meridianoTickets', '0002_auto_20191204_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosParos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('opsiguiente', models.BooleanField(blank=True, db_column='OpSiguiente', null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('paros_grupos_fk', models.IntegerField(blank=True, db_column='Paros_Grupos_fk', null=True)),
                ('oee', models.BooleanField(blank=True, db_column='Oee', null=True)),
                ('disponibilidad', models.BooleanField(blank=True, db_column='Disponibilidad', null=True)),
                ('eficiencia', models.BooleanField(blank=True, db_column='Eficiencia', null=True)),
                ('paropreparacionproducto', models.BooleanField(blank=True, db_column='ParoPreparacionProducto', null=True)),
                ('definicionparos', models.TextField(blank=True, db_column='DefinicionParos', null=True)),
            ],
            options={
                'db_table': 'Codigos_Paros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.CharField(blank=True, max_length=100, null=True)),
                ('aperturaTicket', models.DateTimeField(auto_now_add=True, null=True)),
                ('cierreTicket', models.DateTimeField(blank=True, null=True)),
                ('causa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meridianoTickets.CodigosParos')),
                ('maquinaId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meridianoTickets.Ct', to_field='ct')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
