# Generated by Django 2.2 on 2019-12-05 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meridianoTickets', '0004_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.CharField(blank=True, max_length=100, null=True)),
                ('aperturaTicket', models.DateTimeField(auto_now_add=True, null=True)),
                ('cierreTicket', models.DateTimeField(blank=True, null=True)),
                ('causa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meridianoTickets.CodigosParos')),
                ('maquinaId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meridianoTickets.Ct', to_field='ct')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
