# Generated by Django 2.1 on 2019-12-11 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meridianoTickets', '0004_remove_ticket_estacerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estaCerrado',
            field=models.BooleanField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
