# Generated by Django 2.1 on 2019-12-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meridianoTickets', '0005_ticket_estacerrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='estaCerrado',
        ),
    ]
