# Generated by Django 2.2 on 2019-12-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meridianoTickets', '0007_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='maquinaId',
        ),
    ]
