# Generated by Django 2.2 on 2019-12-06 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meridianoTickets', '0010_remove_ticket_maquinaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='maquinaId',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='meridianoTickets.Ct', to_field='ct'),
            preserve_default=False,
        ),
    ]
